name: Continous Development

on: 
  push:
    branches:
      - production

jobs:
  # label of the container job

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "forum-api-abid" #Must be unique in Heroku
          heroku_email: "abidzarisprivate@gmail.com"