name: Continous Development

on: 
  pull_request:
    branches:
      - main

jobs:
  # label of the container job
  postgres-job-create-production-database:
    # containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `postgres-job` executes in
    container: node:latest

    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
       # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm install

      - name: Create production DB
          # Runs a script that creates a PostgreSQL table, populates
          # the table with data, and then retrieves the data.
        run: |
          psql -h postgres -d ${{ secrets.PGDATABASE_TEST }} -U ${{ secrets.PGUSER }} -W ${{ secrets.PGPASSWORD }} -c 'CREATE DATABASE ${{ secrets.PGDATABASE }};'
        env:
          CI: true
          PGHOST: postgres
          PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
          PGUSER: ${{ secrets.PGUSER }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGPORT: ${{ secrets.PGPORT_TEST }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
          ACCCESS_TOKEN_AGE: ${{ secrets.ACCCESS_TOKEN_AGE }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "forum-api-abid" #Must be unique in Heroku
          heroku_email: "abidzarisprivate@gmail.com"